### ISSUE TITLE
Bot crashes with poor internet connection

### ISSUE THREAD

**Issue by ItsPhant** [ItsPhant/PhantBot#14]
https://github.com/ItsPhant/Dommebot.js/issues/15

**Comment by ItsPhant** [comment]
```
Error: getaddrinfo EAI_AGAIN gateway.discord.gg:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
Emitted 'error' event at:
    at WebSocketConnection.onError (/data/phant/Source/PhantBot-release/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:371:17)
    at WebSocket.onError (/data/phant/Source/PhantBot-release/node_modules/discord.js/node_modules/ws/lib/EventTarget.js:109:16)
    at WebSocket.emit (events.js:180:13)
    at ClientRequest._req.on (/data/phant/Source/PhantBot-release/node_modules/discord.js/node_modules/ws/lib/WebSocket.js:649:10)
    at ClientRequest.emit (events.js:180:13)
    at TLSSocket.socketErrorListener (_http_client.js:394:9)
    at TLSSocket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)

```

**Comment by ItsPhant** [comment]
I ended up just using a systemd service to restart it.
